platform :ios, '10.0'

target 'material-test' do
  use_frameworks!
  pod 'MaterialComponents/TextControls+FilledTextAreas'
  pod 'MaterialComponents/TextControls+FilledTextFields'
  pod 'MaterialComponents/TextControls+OutlinedTextAreas'
  pod 'MaterialComponents/TextControls+OutlinedTextFields'
  pod 'MaterialComponents/TextControls+FilledTextAreasTheming'
  pod 'MaterialComponents/TextControls+FilledTextFieldsTheming'
  pod 'MaterialComponents/TextControls+OutlinedTextAreasTheming'
  pod 'MaterialComponents/TextControls+OutlinedTextFieldsTheming'
end
